name: CI/CD Pipeline

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main, feature/* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        venv/bin/python -m pip install --upgrade pip
        venv/bin/python -m pip install -r requirements.txt

    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/src
      run: |
        source venv/bin/activate
        echo "PYTHONPATH: $PYTHONPATH"
        venv/bin/python -m pytest -v

    - name: Lint code
      run: |
        source venv/bin/activate
        venv/bin/python -m flake8 src tests
